### ISSUE TITLE
Clicking notification doesn't open app

### ISSUE THREAD

**Issue by Bwangster12** [Jerrkawz/google-voice-desktop-app#4] opened 2020-11-16 17:24 UTC
Clicking on a desktop notification when a text is received doesn't open the app.  Nothing happens and you have to manually open the app.

**Comment by Jerrkawz** [comment] 2020-11-19 15:56
Which OS? Works for me on osx

**Comment by Bwangster12** [comment] 2020-11-19 16:00
Windows 10

**Comment by lazyb5** [comment] 2020-11-21 21:58
I can confirm is doesn't open app for me on windows 10.

**Comment by Jerrkawz** [comment] 2020-11-22 04:03
This should be fixed by e4a001 but i won't close it until i do a new release

**Comment by Jerrkawz** [comment] 2020-11-22 04:39
Fixed in 1.0.3

**Closed** 2020-11-22 04:39 UTC

**Comment by rpodric** [comment] 2021-04-04 18:15
It doesn't seem to work on Win10 in 1.1.6, though, but I think it did in 1.1.5.
